# config/routes.yaml

# Redirige la raíz al login
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_login
        permanent: false

controllers:
    resource: routing.controllers

app_login_check:
    path: /login_check
    methods: POST
